// תיאור הטבלאות לצורכי העתקה/גיבוי: סדר בטוח למפתחות זרים + סוגי עמודות
// שדורשים המרה (תאריך / Json / בוליאני). מקור אחד לשני הסקריפטים, כדי שלא
// ייווצר פער בין העתקת הנתונים לגיבוי. מעדכנים כאן בכל שינוי סכמה.
export type ColumnKind = "date" | "json" | "bool" | "scalar";

export type ModelSpec = {
  /** שם הטבלה במסד */
  table: string;
  /** שם המודל בלקוח Prisma (prisma[model]) */
  model: string;
  columns: Record<string, ColumnKind>;
  /**
   * טבלה שמסד טרי כבר מגיע איתה מלאה (מיגרציה/זריעה) — ולכן שורות בה אינן
   * "יעד מאוכלס" שחוסם שחזור. רשומות אלה נדרסות בשחזור עצמו לפי id.
   */
  seeded?: boolean;
  /**
   * מפתחות עסקיים ייחודיים (@unique/@@unique שאינם ה-id). מסד יעד שכבר
   * נזרע (‏deploy:prepare / db:setup) מחזיק את אותם מפתחות תחת cuid-ים
   * חדשים, ושחזור לפי id בלבד היה נופל על הפרת ייחודיות — לכן השחזור
   * מיישר לפיהם שורת יעד מתנגשת לפני הכתיבה. מפתח עם ערך null לא נאכף
   * כייחודי ב-Postgres ולכן מדולג.
   */
  businessKeys?: string[][];
  /**
   * מי מפנה לשורה כאן (מודל Prisma + עמודת המפתח הזר) — קובע בשחזור אם
   * שורה מתנגשת ביעד נמחקת (אין הפניות) או מקבלת את מזהה הגיבוי.
   */
  refs?: { model: string; field: string }[];
};

/** סדר ההוספה — הורה לפני ילד. המחיקה נעשית בסדר ההפוך. */
export const MODELS: ModelSpec[] = [
  {
    // אבן דרך 8: כל הנתונים האישיים תלויים במשתמש, ולכן הוא ראשון בסדר
    table: "User",
    model: "user",
    seeded: true,
    businessKeys: [["googleSub"]],
    refs: [
      { model: "capacityProfile", field: "userId" },
      { model: "exerciseTrack", field: "userId" },
      { model: "exerciseLoadState", field: "userId" },
      { model: "gameState", field: "userId" },
      { model: "gameRun", field: "userId" },
      { model: "gameLedger", field: "userId" },
      { model: "proWorkspace", field: "ownerId" },
      { model: "proMembership", field: "userId" },
      { model: "proInvite", field: "createdById" },
      { model: "proInvite", field: "acceptedById" },
      { model: "proTag", field: "traineeId" },
      { model: "proTag", field: "authorId" },
      { model: "proSessionMeta", field: "traineeId" },
      { model: "proSessionMeta", field: "scheduledById" },
      { model: "proSessionAudit", field: "actorId" },
      { model: "proComment", field: "authorId" },
      { model: "invite", field: "userId" },
      { model: "locationProfile", field: "userId" },
      { model: "userCalibration", field: "userId" },
      { model: "benchmark", field: "userId" },
      { model: "session", field: "userId" },
      { model: "setLog", field: "userId" },
      { model: "benchmarkResult", field: "userId" },
      { model: "legalAcceptance", field: "userId" },
      { model: "feedback", field: "userId" },
      { model: "experienceProfile", field: "userId" },
      { model: "experienceSession", field: "userId" },
      { model: "experienceFeedback", field: "userId" },
      { model: "experienceAward", field: "userId" },
      { model: "challenge", field: "createdById" },
      { model: "challengeMember", field: "userId" },
      { model: "match", field: "hostId" },
      { model: "matchParticipant", field: "userId" },
    ],
    columns: {
      id: "scalar",
      name: "scalar",
      role: "scalar",
      createdAt: "date",
      lastSeenAt: "date",
      revokedAt: "date",
      disclaimerAcceptedAt: "date",
      googleSub: "scalar",
      email: "scalar",
      legalVersion: "scalar",
      healthScreenedAt: "date",
      healthScreenVersion: "scalar",
      healthFlagged: "bool",
      healthAnswers: "json",
      signupSource: "scalar",
      trainingPreferences: "json",
      displayName: "scalar",
    },
  },
  {
    table: "Invite",
    model: "invite",
    businessKeys: [["code"], ["userId"]],
    columns: {
      id: "scalar",
      code: "scalar",
      label: "scalar",
      createdAt: "date",
      usedAt: "date",
      revokedAt: "date",
      userId: "scalar",
    },
  },
  {
    table: "Exercise",
    model: "exercise",
    seeded: true,
    // התרגילים נזרעים בכל פריסה (deploy:prepare) לפי slug עם cuid חדש —
    // התרחיש המרכזי שהיישור בשחזור נועד לו
    businessKeys: [["slug"]],
    refs: [{ model: "setLog", field: "exerciseId" }],
    columns: {
      id: "scalar",
      slug: "scalar",
      nameHe: "scalar",
      nameEn: "scalar",
      sourceId: "scalar",
      licenseNote: "scalar",
      trainingType: "scalar",
      provenanceId: "scalar",
      modality: "scalar",
      pattern: "scalar",
      equipment: "json",
      stationType: "scalar",
      skillLevel: "scalar",
      loadClass: "scalar",
      unilateral: "bool",
      repPaceSecPerRep: "scalar",
      systemicCost: "scalar",
      constraints: "json",
      substitutes: "json",
      scalingEasierId: "scalar",
      scalingHarderId: "scalar",
      instructionsHe: "scalar",
      primaryMuscles: "json",
      secondaryMuscles: "json",
      createdAt: "date",
    },
  },
  {
    table: "LocationProfile",
    model: "locationProfile",
    columns: {
      id: "scalar",
      userId: "scalar",
      kind: "scalar",
      name: "scalar",
      equipment: "json",
      quantities: "json",
      peakHours: "bool",
      constraints: "json",
      usuallyTaken: "json",
      weightInventory: "json",
    },
  },
  {
    table: "UserCalibration",
    model: "userCalibration",
    columns: {
      id: "scalar",
      userId: "scalar",
      repsPerMinute: "json",
      failurePoints: "json",
      maxReps: "json",
      level: "scalar",
      paceFactor: "scalar",
      baselineLoads: "json",
      testedMax: "json",
      bodyWeightKg: "scalar",
      heightCm: "scalar",
      source: "scalar",
      createdAt: "date",
    },
  },
  {
    table: "Benchmark",
    model: "benchmark",
    // נזרע בכניסה הראשונה לאפליקציה (src/lib/benchmarks.ts) — כניסה לפני
    // שחזור מייצרת רשומות עם אותו userId+slug ומזהים אחרים
    businessKeys: [["userId", "slug"]],
    refs: [{ model: "benchmarkResult", field: "benchmarkId" }],
    columns: {
      id: "scalar",
      userId: "scalar",
      slug: "scalar",
      nameHe: "scalar",
      structure: "json",
      cadenceWeeks: "scalar",
      lastDeclinedAt: "date",
    },
  },
  {
    table: "Session",
    model: "session",
    refs: [
      { model: "movementReceipt", field: "sessionId" },
      { model: "sessionWriteReceipt", field: "sessionId" },
      { model: "proSessionMeta", field: "sessionId" },
      { model: "proSessionAudit", field: "sessionId" },
      { model: "proComment", field: "sessionId" },
    ],
    columns: {
      gameBudgetSec: "scalar",
      id: "scalar",
      userId: "scalar",
      date: "date",
      seed: "scalar",
      timeBudgetMin: "scalar",
      locationId: "scalar",
      mood: "scalar",
      status: "scalar",
      revision: "scalar",
      score: "scalar",
      rpe: "scalar",
      funRating: "scalar",
      explainLog: "json",
      context: "json",
      startedAt: "date",
      completedAt: "date",
      createdAt: "date",
    },
  },
  {
    table: "Block",
    model: "block",
    businessKeys: [["sessionId", "order"]],
    refs: [{ model: "setLog", field: "blockId" }],
    columns: {
      id: "scalar",
      sessionId: "scalar",
      order: "scalar",
      type: "scalar",
      format: "scalar",
      plannedMin: "scalar",
      payload: "json",
    },
  },
  {
    table: "SetLog",
    model: "setLog",
    businessKeys: [["blockId", "exerciseId", "setIndex"]],
    refs: [{ model: 'sessionWriteReceipt', field: 'setLogId' }],
    columns: {
      capacityEvidence: "json",
      actualDoseSec: "scalar",
      revision:'scalar', reportedAt:'date', effectiveAt:'date', timingSource:'scalar', reportedOnTime:'bool', reportedTempo:'bool', interrupted:'bool',
      recordKind: "scalar",
      gameplayEligible: "bool", gameplayUnits: "scalar",
      id: "scalar",
      userId: "scalar",
      blockId: "scalar",
      exerciseId: "scalar",
      setIndex: "scalar",
      targetReps: "scalar",
      actualReps: "scalar",
      targetWeightKg: "scalar",
      actualWeightKg: "scalar",
      effort: "scalar",
      workSec: "scalar",
      restSec: "scalar",
      completedAt: "date",
    },
  },
  { table:'SessionWriteReceipt', model:'sessionWriteReceipt', businessKeys:[['sessionId','requestId']],
    columns:{ id:'scalar',sessionId:'scalar',requestId:'scalar',payloadHash:'scalar',setLogId:'scalar',createdAt:'date' } },
  {
    table: "SwapEvent",
    model: "swapEvent",
    columns: {
      id: "scalar",
      sessionId: "scalar",
      blockId: "scalar",
      fromExerciseId: "scalar",
      toExerciseId: "scalar",
      reason: "scalar",
      midWorkout: "bool",
      createdAt: "date",
      resolvedAt: "date",
      needsReview: "bool",
    },
  },
  {
    table: "BenchmarkResult",
    model: "benchmarkResult",
    businessKeys: [["sessionId"]],
    columns: {
      id: "scalar",
      userId: "scalar",
      benchmarkId: "scalar",
      sessionId: "scalar",
      scoreValue: "scalar",
      scoreUnit: "scalar",
      createdAt: "date",
    },
  },
  {
    // רישום הגיבויים עצמו נכלל בגיבוי: כך היסטוריית ההרצות שורדת שחזור.
    table: "BackupRun",
    model: "backupRun",
    columns: {
      id: "scalar",
      finishedAt: "date",
      source: "scalar",
      rows: "scalar",
      bytes: "scalar",
      target: "scalar",
      status: "scalar",
      error: "scalar",
    },
  },
  {
    // הפיילוט הציבורי (סבב 35). יומן האישורים המשפטיים תלוי במשתמש, ולכן
    // אחריו; שלוש האחרות עצמאיות ומיקומן בסוף אינו משנה.
    table: "LegalAcceptance",
    model: "legalAcceptance",
    columns: {
      id: "scalar",
      userId: "scalar",
      version: "scalar",
      acceptedAt: "date",
    },
  },
  {
    // המשוב נשמר בגיבוי כמו כל שאר הנתונים; userId ריק = פנייה מאנונימי
    table: "Feedback",
    model: "feedback",
    columns: {
      id: "scalar",
      userId: "scalar",
      sessionId: "scalar",
      kind: "scalar",
      rating: "scalar",
      name: "scalar",
      email: "scalar",
      text: "scalar",
      path: "scalar",
      createdAt: "date",
      resolvedAt: "date",
    },
  },
  {
    // אירועי הפיילוט: בלי מפתח זר למשתמש (הם שורדים מחיקת חשבון), ולכן
    // גם בלי refs — אף אחד לא מפנה אליהם.
    table: "PilotEvent",
    model: "pilotEvent",
    columns: {
      id: "scalar",
      name: "scalar",
      userId: "scalar",
      userRole: "scalar",
      visitId: "scalar",
      path: "scalar",
      props: "json",
      createdAt: "date",
    },
  },
  {
    // הגדרות המערכת (כרגע רק שורת "registration"): המפתח הלוגי הוא key,
    // ולכן הוא מפתח עסקי שהשחזור מיישר לפיו — ה-id נשאר cuid כמו בכולן.
    table: "AppSetting",
    model: "appSetting",
    businessKeys: [["key"]],
    columns: {
      id: "scalar",
      key: "scalar",
      value: "json",
      updatedAt: "date",
    },
  },
  {
    // חוויית האימון (C1): פרופיל אחד למשתמש — userId הוא המפתח העסקי
    table: "ExperienceProfile",
    model: "experienceProfile",
    businessKeys: [["userId"]],
    columns: {
      id: "scalar",
      userId: "scalar",
      enabled: "bool",
      revision: "scalar",
      prefs: "json",
      previous: "json",
      dayOverride: "json",
      suggestion: "json",
      nextPlan: "json",
      contentVersion: "scalar",
      createdAt: "date",
      updatedAt: "date",
    },
  },
  {
    // קישור אימון לחוויה — אחרי Session (מפתח זר) ואחרי User
    table: "ExperienceSession",
    model: "experienceSession",
    businessKeys: [["sessionId"]],
    columns: {
      id: "scalar",
      sessionId: "scalar",
      userId: "scalar",
      experienceVersion: "scalar",
      contentVersion: "scalar",
      profileRevision: "scalar",
      overrides: "json",
      resolved: "json",
      outcome: "scalar",
      journeyStep: "scalar",
      createdAt: "date",
      endedAt: "date",
    },
  },
  {
    table: "ExperienceFeedback",
    model: "experienceFeedback",
    businessKeys: [["sessionId", "question"]],
    columns: {
      id: "scalar",
      userId: "scalar",
      sessionId: "scalar",
      question: "scalar",
      answer: "scalar",
      createdAt: "date",
    },
  },
  {
    // הענקה אידמפוטנטית: (userId, kind, key) ייחודי
    table: "ExperienceAward",
    model: "experienceAward",
    businessKeys: [["userId", "kind", "key"]],
    columns: {
      id: "scalar",
      userId: "scalar",
      kind: "scalar",
      key: "scalar",
      amount: "scalar",
      period: "scalar",
      sessionId: "scalar",
      createdAt: "date",
    },
  },
  // החלטה 47: אתגרים וזירה. guestTokenHash מגובה — hash, לא סוד.
  {
    table: "Challenge",
    model: "challenge",
    businessKeys: [["code"]],
    refs: [{ model: "challengeMember", field: "challengeId" }],
    columns: {
      id: "scalar",
      code: "scalar",
      title: "scalar",
      kind: "scalar",
      benchmarkSlug: "scalar",
      startDay: "scalar",
      endDay: "scalar",
      createdById: "scalar",
      endedAt: "date",
      createdAt: "date",
    },
  },
  {
    table: "ChallengeMember",
    model: "challengeMember",
    businessKeys: [["challengeId", "userId"]],
    columns: {
      id: "scalar",
      challengeId: "scalar",
      userId: "scalar",
      joinedAt: "date",
    },
  },
  {
    table: "Match",
    model: "match",
    businessKeys: [["code"]],
    refs: [
      { model: "matchParticipant", field: "matchId" },
      { model: "matchResult", field: "matchId" },
    ],
    columns: {
      id: "scalar",
      code: "scalar",
      hostId: "scalar",
      phase: "scalar",
      program: "json",
      programRevision: "scalar",
      seed: "scalar",
      proposalRound: "scalar",
      strategyDeadline: "date",
      eventIndex: "scalar",
      heat: "scalar",
      stage: "scalar",
      startsAt: "date",
      revision: "scalar",
      createdAt: "date",
      endedAt: "date",
    },
  },
  {
    table: "MatchParticipant",
    model: "matchParticipant",
    businessKeys: [["guestTokenHash"], ["matchId", "userId"]],
    refs: [{ model: "matchResult", field: "participantId" }],
    columns: {
      id: "scalar",
      matchId: "scalar",
      userId: "scalar",
      guestName: "scalar",
      guestTokenHash: "scalar",
      managedById: "scalar",
      guestAckAt: "date",
      guestHealthFlagged: "bool",
      guestHealthAcknowledged: "bool",
      role: "scalar",
      teamId: "scalar",
      captain: "bool",
      readyRevision: "scalar",
      picks: "json",
      jokerEvent: "scalar",
      strategyLockedAt: "date",
      order: "scalar",
      joinedAt: "date",
    },
  },
  {
    table: "MatchResult",
    model: "matchResult",
    businessKeys: [["participantId", "eventIndex"]],
    columns: {
      id: "scalar",
      matchId: "scalar",
      participantId: "scalar",
      eventIndex: "scalar",
      value: "scalar",
      status: "scalar",
      by: "scalar",
      confirmedAt: "date",
      createdAt: "date",
    },
  },
  { table: "ExerciseTrack", model: "exerciseTrack", businessKeys: [["userId", "slug", "band"]], columns: { id: "scalar", userId: "scalar", slug: "scalar", band: "scalar", data: "json", updatedAt: "date" } },
  { table: "CapacityProfile", model: "capacityProfile", businessKeys: [["userId"]], columns: { id: "scalar", userId: "scalar", revision: "scalar", data: "json", updatedAt: "date" } },
  { table: "MovementReceipt", model: "movementReceipt", businessKeys: [["sessionId", "requestId"]], columns: { id: "scalar", sessionId: "scalar", requestId: "scalar", payloadHash: "scalar", result: "json", createdAt: "date" } },
  { table: "ExerciseLoadState", model: "exerciseLoadState", businessKeys: [["userId"]], columns: { id: "scalar", userId: "scalar", data: "json", lastSessionDay: "scalar", updatedAt: "date" } },
  { table: "GameState", model: "gameState", businessKeys: [["userId"]], columns: { id: "scalar", userId: "scalar", revision: "scalar", materials: "scalar", keys: "scalar", tool: "bool", challengeStage: "scalar", buildStage: "scalar", world:'json', updatedAt: "date" } },
  { table: "GameRun", model: "gameRun", businessKeys: [["sessionId"]], columns: { id: "scalar", userId: "scalar", sessionId: "scalar", factor: "scalar", awardedMaterials: "scalar", awardedKeys: "scalar", progress: "scalar", result: "scalar", createdAt: "date" } },
  { table: "GameLedger", model: "gameLedger", businessKeys: [["userId", "key"]], columns: { id: "scalar", userId: "scalar", key: "scalar", kind: "scalar", materials: "scalar", keys: "scalar", detail: "json", createdAt: "date" } },
  { table: "ProWorkspace", model: "proWorkspace", refs: [{ model: "proMembership", field: "workspaceId" }, { model: "proInvite", field: "workspaceId" }, { model: "proTag", field: "workspaceId" }, { model: "proSessionMeta", field: "workspaceId" }], columns: { id: "scalar", name: "scalar", kind: "scalar", ownerId: "scalar", timezone: "scalar", equipment: "json", createdAt: "date", archivedAt: "date" } },
  { table: "ProMembership", model: "proMembership", businessKeys: [["workspaceId", "userId", "role"]], columns: { id: "scalar", workspaceId: "scalar", userId: "scalar", role: "scalar", acceptedAt: "date", revokedAt: "date", createdAt: "date" } },
  { table: "ProInvite", model: "proInvite", businessKeys: [["tokenHash"]], columns: { id: "scalar", workspaceId: "scalar", tokenHash: "scalar", role: "scalar", createdById: "scalar", acceptedById: "scalar", expiresAt: "date", createdAt: "date", acceptedAt: "date", revokedAt: "date" } },
  { table: "ProTag", model: "proTag", columns: { id: "scalar", workspaceId: "scalar", traineeId: "scalar", authorId: "scalar", kind: "scalar", code: "scalar", label: "scalar", createdAt: "date", archivedAt: "date" } },
  { table: "ProSessionMeta", model: "proSessionMeta", businessKeys: [["sessionId"]], columns: { id: "scalar", sessionId: "scalar", workspaceId: "scalar", traineeId: "scalar", scheduledById: "scalar", timezone: "scalar", scheduledAt: "date", cancelledAt: "date", createdAt: "date" } },
  { table: "ProSessionAudit", model: "proSessionAudit", columns: { id: "scalar", sessionId: "scalar", actorId: "scalar", action: "scalar", revision: "scalar", before: "json", after: "json", createdAt: "date" } },
  { table: "ProComment", model: "proComment", columns: { id: "scalar", sessionId: "scalar", authorId: "scalar", body: "scalar", createdAt: "date" } },
];
